language: python
python:
- "3.6"

install:
- sudo pip install pylint

script:
- pylint brittle.py
- echo Testing encryption and decryption
- python brittle.py brittle.py brittle.dat
- python brittle.py brittle.dat brittle.decr.py --decode
